export const VS_CODE_RECOMMENDATIONS = [
    "formulahendry.auto-rename-tag",
    "aaron-bond.better-comments",
    "usernamehw.errorlens",
    "mquandalle.graphql",
    "vincaslt.highlight-matching-tag",
    "fractalbrew.backticks",
    "streetsidesoftware.code-spell-checker",
    "dbaeumer.vscode-eslint",
    "eamodio.gitlens",
    "visualstudioexptteam.vscodeintellicode",
    "ms-vsliveshare.vsliveshare",
    "christian-kohler.path-intellisense",
    "esbenp.prettier-vscode",
    "yoavbls.pretty-ts-errors",
    "sibiraj-s.vscode-scss-formatter",
    "stylelint.vscode-stylelint",
    "shardulm94.trailing-spaces"
];