---
name: Feature request
description: You have and idea on how to improve this project? Let us know!
title: 'Feature title'
labels: [Core, Type: feature]
body:
  - type: textarea
    id: use_case
    attributes:
      label: 'Is your feature request related to a problem?'
      description: "A clear and concise description of what the problem is."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like to see"
      description: 'Describe on how would you solve this issue or share an idea for it.'
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 'Additional context'
      description: 'Add any other context or screenshots about the feature request.'
    validations:
      required: false
