import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Cache same-origin image requests
registerRoute(
    ({ url }) => (
        url.origin === self.location.origin
        // cache png, gif, jpeg, jpg in image cache
        && /.(jpe?g|png|gif)$/.test(url.pathname)
    ),
    new StaleWhileRevalidate({
        cacheName: 'images',
        plugins: [
            // Ensure that once this runtime cache reaches a maximum size the
            // least-recently used images are removed.
            new ExpirationPlugin({ maxEntries: 50 })
        ]
    })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

const RESPONSE_OK = 200;

const makeRequestAndUpdateCache = async (request, cache) => {
    const response = await fetch(request);
    const isValid = response.status === RESPONSE_OK;
    const responseToCache = response.clone();

    if (isValid) {
        cache.put(request.url, responseToCache);
    }

    return response;
};

const updateWithFreshDataViaBroadCast = async (request, cache) => {
    const type = request.headers.get('Application-Model');
    const revalidatedResponse = await makeRequestAndUpdateCache(request, cache);
    const responseClone = revalidatedResponse.clone();

    const broadcast = new BroadcastChannel(type);
    broadcast.postMessage({ payload: await responseClone.json(), type });
    broadcast.close();
};

registerRoute(
    /\/graphql/,
    async ({ event }) => {
        const { request } = event;
        const cache = await caches.open('graphql');
        const responseCache = await cache.match(request);

        if (!responseCache) {
            // if there is no cached response (notice, we return promise)
            return makeRequestAndUpdateCache(request, cache);
        }

        // Give imidiate response & revalidate it
        updateWithFreshDataViaBroadCast(request, cache);

        return responseCache;
    }
);

// respond to document request only in offline
registerRoute(
    ({ request }) => {
        const { url, destination } = request;
        const { hostname } = new URL(url);

        if (destination !== 'document') { // skip all NON documents
            return false;
        }

        if (hostname !== self.location.hostname) { // skip requests to other domains
            return false;
        }

        return true;
    },
    async ({ event }) => {
        const { request } = event;

        const cache = await caches.open(self.CACHE_NAME);
        const responseFromCache = await cache.match('/');

        if (!navigator.onLine) {
            return responseFromCache; // respond from cache
        }

        if (!responseFromCache) {
            const rootResponse = await fetch('/'); // respond from server

            if (rootResponse.status === RESPONSE_OK) { // cache only 200 responses
                cache.put('/', rootResponse.clone());
            }
        }

        return fetch(request); // respond from server
    }
);