/**
 * ScandiPWA - Progressive Web App for Magento
 *
 * Copyright © Scandiweb, Inc. All rights reserved.
 * See LICENSE for license details.
 *
 * @license OSL-3.0 (Open Software License ("OSL") v. 3.0)
 * @package scandipwa/base-theme
 * @link https://github.com/scandipwa/base-theme
 */

import Event from './Event';
import {
    EVENT_GTM_PRODUCT_ADD_TO_CART,
    EVENT_GTM_CHECKOUT,
    EVENT_GTM_IMPRESSIONS_PLP,
    EVENT_GTM_IMPRESSIONS_HOME,
    EVENT_GTM_IMPRESSIONS_CROSS_SELL,
    EVENT_GTM_IMPRESSIONS_WISHLIST,
    EVENT_GTM_IMPRESSIONS_SEARCH,
    EVENT_GTM_PRODUCT_CLICK,
    EVENT_GTM_PRODUCT_DETAIL,
    EVENT_GTM_PURCHASE,
    EVENT_GTM_PRODUCT_REMOVE_FROM_CART,
    EVENT_GTM_GENERAL_INIT
} from './Events';

export {
    Event,
    EVENT_GTM_PRODUCT_ADD_TO_CART,
    EVENT_GTM_CHECKOUT,
    EVENT_GTM_IMPRESSIONS_PLP,
    EVENT_GTM_IMPRESSIONS_HOME,
    EVENT_GTM_IMPRESSIONS_CROSS_SELL,
    EVENT_GTM_IMPRESSIONS_WISHLIST,
    EVENT_GTM_IMPRESSIONS_SEARCH,
    EVENT_GTM_PRODUCT_CLICK,
    EVENT_GTM_PRODUCT_DETAIL,
    EVENT_GTM_PURCHASE,
    EVENT_GTM_PRODUCT_REMOVE_FROM_CART,
    EVENT_GTM_GENERAL_INIT
};
