/**
 * ScandiPWA - Progressive Web App for Magento
 *
 * Copyright © Scandiweb, Inc. All rights reserved.
 * See LICENSE for license details.
 *
 * @license OSL-3.0 (Open Software License ("OSL") v. 3.0)
 * @package scandipwa/base-theme
 * @link https://github.com/scandipwa/base-theme
 */

import Event from './Event';
import {
    EVENT_GTM_PRODUCT_ADD_TO_CART,
    EVENT_GTM_CHECKOUT,
    EVENT_GTM_CHECKOUT_OPTION,
    EVENT_GTM_IMPRESSIONS_PLP,
    EVENT_GTM_IMPRESSIONS_HOME,
    EVENT_GTM_IMPRESSIONS_CROSS_SELL,
    EVENT_GTM_IMPRESSIONS_WISHLIST,
    EVENT_GTM_IMPRESSIONS_SEARCH,
    EVENT_GTM_ORDER_DATA,
    EVENT_GTM_PRODUCT_CLICK,
    EVENT_GTM_PRODUCT_DETAIL,
    EVENT_GTM_PURCHASE,
    EVENT_GTM_PRODUCT_REMOVE_FROM_CART,
    EVENT_GTM_PROMOTION_VIEW,
    EVENT_GTM_PROMOTION_CLICK,
    EVENT_GTM_SUPPLEMENTAL_USER_LOGIN,
    EVENT_GTM_SUPPLEMENTAL_USER_REGISTER,
    EVENT_GTM_SUPPLEMENTAL_ADD_TO_WISHLIST,
    EVENT_GTM_SUPPLEMENTAL_USER_CHECKOUT_DATA,
    EVENT_GTM_META_UPDATE,
    EVENT_GTM_PRODUCT_HOVER,
    EVENT_GTM_URL_REWRITE,
    EVENT_GTM_ROUTE_HANDLE,
    EVENT_GTM_IMPRESSIONS_LINKED,
    EVENT_GTM_GENERAL_INIT
} from './Events';

export {
    Event,

    // GTM
    EVENT_GTM_PRODUCT_ADD_TO_CART,
    EVENT_GTM_CHECKOUT,
    EVENT_GTM_CHECKOUT_OPTION,
    EVENT_GTM_IMPRESSIONS_PLP,
    EVENT_GTM_IMPRESSIONS_HOME,
    EVENT_GTM_IMPRESSIONS_CROSS_SELL,
    EVENT_GTM_IMPRESSIONS_WISHLIST,
    EVENT_GTM_IMPRESSIONS_SEARCH,
    EVENT_GTM_ORDER_DATA,
    EVENT_GTM_PRODUCT_CLICK,
    EVENT_GTM_PRODUCT_DETAIL,
    EVENT_GTM_PURCHASE,
    EVENT_GTM_PRODUCT_REMOVE_FROM_CART,
    EVENT_GTM_PROMOTION_VIEW,
    EVENT_GTM_PROMOTION_CLICK,
    EVENT_GTM_SUPPLEMENTAL_USER_LOGIN,
    EVENT_GTM_SUPPLEMENTAL_USER_REGISTER,
    EVENT_GTM_SUPPLEMENTAL_ADD_TO_WISHLIST,
    EVENT_GTM_SUPPLEMENTAL_USER_CHECKOUT_DATA,
    EVENT_GTM_META_UPDATE,
    EVENT_GTM_PRODUCT_HOVER,
    EVENT_GTM_URL_REWRITE,
    EVENT_GTM_ROUTE_HANDLE,
    EVENT_GTM_IMPRESSIONS_LINKED,
    EVENT_GTM_GENERAL_INIT
};
