<?php
    $colorConfig = $this->getThemeConfiguration('color_customization');
    $contentConfig = $this->getThemeConfiguration('content_customization');
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <script>
            window.storeList = JSON.parse(`<?= $this->getStoreListJson() ?>`);
            window.storeRegexText = `/(${window.storeList.join('|')})?`;
        </script>

        <script>
            if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                    navigator.serviceWorker.register('/sw.js');
                });
            }

            window.actionName = {
                type: `<?= $this->getAction(); ?>`
            };

            window.contentConfiguration = <?= json_encode($contentConfig) ?> || {};
        </script>
        <script async src="<?= $this->getStaticFile("assets/pwacompat.min.js"); ?>"></script>

        <!-- TODO: Find or implement helper to generate fonts related code -->
        <!-- <link rel="preload" href="<?= $this->getStaticFile("assets/font/Muli-Light.ttf"); ?>" as="font" type="font/ttf" crossorigin="">
        <link rel="preload" href="<?= $this->getStaticFile("assets/font/Muli-Regular.ttf"); ?>" as="font" type="font/ttf" crossorigin="">
        <link rel="preload" href="<?= $this->getStaticFile("assets/font/Muli-SemiBold.ttf"); ?>" as="font" type="font/ttf" crossorigin="">
        <link rel="preload" href="<?= $this->getStaticFile("assets/font/Muli-Bold.ttf"); ?>" as="font" type="font/ttf" crossorigin=""> -->

        <style>
            <?php if ($colorConfig['enable_color_customization']['enable_custom_colors'] !== "0"): ?>
                <?php $colorArray = $colorConfig['primary_colors'] + $colorConfig['secondary_colors']; ?>
                :root {
                    <?php foreach ($colorArray as $code => $color): ?>
                        <?php if (strpos($code, 'color') !== false): ?>
                            <?= sprintf('--imported_%s: #%s;', $code, $color); ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                }
            <?php endif; ?>

            @font-face {
                font-family: 'Muli';
                font-weight: 300;
                font-display: fallback;
                src: local('Muli Light'), local('Muli-Light'), url(<%= htmlWebpackPlugin.options.publicPath %>assets/font/Muli-Light.ttf) format('truetype');
            }

            @font-face {
                font-family: 'Muli';
                font-weight: normal;
                font-display: fallback;
                src: local('Muli Regular'), local('Muli-Regular'), url(<%= htmlWebpackPlugin.options.publicPath %>assets/font/Muli-Regular.ttf) format('truetype');
            }

            @font-face {
                font-family: 'Muli';
                font-weight: 600;
                font-display: fallback;
                src: local('Muli SemiBold'), local('Muli-SemiBold'), url(<%= htmlWebpackPlugin.options.publicPath %>assets/font/Muli-SemiBold.ttf) format('truetype');
            }

            @font-face {
                font-family: 'Muli';
                font-weight: bold;
                font-display: fallback;
                src: local('Muli Bold'), local('Muli-Bold'), url(<%= htmlWebpackPlugin.options.publicPath %>assets/font/Muli-Bold.ttf) format('truetype');
            }
        </style>

        <link rel="shortcut icon" href="<?= $this->getStaticFile("assets/favicon/favicon.ico"); ?>">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover">
    </head>

    <body>
        <noscript> You need to enable JavaScript to run this app. </noscript>
        <div id="root"></div>
        <script src="<?= $this->getStaticBundleFile() ?>"></script>
    </body>
</html>
